// CSE 154 ASCIIMation
// This is my custom animation to be used by the overall program.
// It was automatically generated by the StringMaker tool.
// (Paste this code as the contents of your myanimation.js file.)

var CUSTOM =
"_______\n" + 
"\\...../\n" + 
" \\.../\n" + 
"  \\./\n" + 
"  / \\\n" + 
" /   \\\n" + 
"/     \\\n" + 
"\"\"\"\"\"\"\"\n" + 
"=====\n" + 
"_______\n" + 
"\\     /\n" + 
" \\.../\n" + 
"  \\./\n" + 
"  / \\\n" + 
" /   \\\n" + 
"/.....\\\n" + 
"\"\"\"\"\"\"\"\n" + 
"=====\n" + 
"_______\n" + 
"\\     /\n" + 
" \\   /\n" + 
"  \\./\n" + 
"  / \\\n" + 
" /...\\\n" + 
"/.....\\\n" + 
"\"\"\"\"\"\"\"\n" + 
"=====\n" + 
"_______\n" + 
"\\     /\n" + 
" \\   /\n" + 
"  \\ /\n" + 
"  /.\\\n" + 
" /...\\\n" + 
"/.....\\\n" + 
"\"\"\"\"\"\"\"\n" + 
"=====\n";

ANIMATIONS["Custom"] = ANIMATIONS["custom"] = ANIMATIONS["CUSTOM"] = CUSTOM;
